[phases.setup]
nixPkgs = ["nodejs_20", "python3"]

[phases.install]
cmds = ["npm ci --legacy-peer-deps --ignore-scripts"]

[phases.build]
cmds = ["rm -rf node_modules/.cache && npm run build"]

[start]
cmd = "npm start"
