[phases.setup]
nixPkgs = ["nodejs_20", "npm-10_x", "python3", "python3Packages.pip"]

[phases.install]
cmds = ["npm ci --legacy-peer-deps"]

[phases.build]
cmds = ["npm run build"]

[start]
cmd = "npm start"
