[phases.setup]
nixPkgs = ["nodejs_20", "python3", "gcc", "g++", "make", "pkg-config", "libusb1"]

[phases.install]
cmds = ["npm ci --legacy-peer-deps"]

[phases.build]
cmds = ["npm run build"]

[start]
cmd = "npm start"
