[phases.setup]
nixPkgs = ["nodejs_22", "npm-9_x"]

[phases.install]
cmds = ["npm i"]

[phases.build]
cmds = ["apt-get update && apt-get install -y python3 python3-pip && npm install && npm run build"]

[start]
cmd = "npm run start"
